/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jsierra3991.functional.programming;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
