version: '3'

services:
  database:
    build: database
    container_name: postgres-platzi
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: platzi_go
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  application:
    build: .
    container_name: platzi_go_server
    ports:
      - "5060:5060"
